---
output: 
  md_document:
    variant: markdown_github
---

## Trabajo en equipo para la asignatura "Big Data"

Repo utilizado para elaborar el trabajo en equipo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2020-2021. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-20-21-web/>.

<!-- El párrafo de arriba has de dejarlo tal cual. No has de cambiar nada!!-->

<!-- En la linea de abajo has de sustituir "perezp44" por tu usuario de Github-->
La versión final del trabajo puede visualizarse en: <https://rodri45l.github.io/trabajo_BigData_equipo/>. 


<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, tenéis que poner el título del trabajo y el nombre de los componentes del equipo-->

El título del trabajo es *Análisis del impacto ecológico*
El objetivo de este trabajo es mostrar la evolución y el impacto de algunas variables medioambientales relevantes (las emisiones del CO2, estudiaremos su evolución así como las principales causas de sus aumentos y que países son los principales responsables) y ver el impacto negativo que provoca a nivel medioambiental en el mundo y como esto nos afecta (incrementos de temperatura). También veremos brevemente la evolución de las energias renovables a nivel mundial.


<!-- Finalmente, acuérdate que cuando hayas hecho los cambios y hayas dejado este archivo como hayáis decidido, TENEIS que knittearlo para que los cambio se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github-->

